# Translations template for pypowervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.0.0.4\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-09-05 04:30-0400\n"
"PO-Revision-Date: 2016-09-05 04:30-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: pypowervm/adapter.py:132
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "Protocole non valide \"%s\""

#: pypowervm/adapter.py:138
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "Communication non chiffrée avec PowerVM. Passez la configuration en https."

#: pypowervm/adapter.py:152
msgid "Calculating default audit memento failed, using 'default'."
msgstr "Echec du calcul du mémento d'audit par défaut, utilisation de 'default'."

#: pypowervm/adapter.py:187
msgid "Local authentication not supported on HMC."
msgstr "Authentification locale non prise en charge sur la console HMC."

#: pypowervm/adapter.py:206
#, python-format
msgid "Setting up event listener for %s"
msgstr "Configuration du programme d'écoute d'événement pour %s"

#: pypowervm/adapter.py:245
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "Descripteur de fichier inattendu sur la demande %s"

#: pypowervm/adapter.py:298
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "Erreur inattendue pour %(meth)s %(url)s"

#: pypowervm/adapter.py:300
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "Erreur inattendue : %(class)s pour %(method)s %(url)s : %(excp)s"

#: pypowervm/adapter.py:338
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer "
"be used."
msgstr ""
"La reconnexion a été jugée non sécurisée. Cette instance de session "
"ne doit plus être utilisée."

#: pypowervm/adapter.py:348
#, python-format
msgid "Attempting re-login %s"
msgstr "Tentative de reconnexion à %s"

#: pypowervm/adapter.py:359
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"Reconnexion 401, corps de réponse :\n"
"%s"

#: pypowervm/adapter.py:364
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"Echec de reconnexion, corps de réponse :\n"
"%s"

#: pypowervm/adapter.py:368
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"Echec de la reconnexion :\n"
"%s"

#: pypowervm/adapter.py:387
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"Echec nouvelle tentative avec à nouveau 401, corps de réponse :\n"
"%s"

#: pypowervm/adapter.py:390
#, python-format
msgid "suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr "Réponse HTTP 401 suspecte pour %(method)s %(path)s : jeton totalement nouveau"

#: pypowervm/adapter.py:432
#, python-format
msgid ""
"Failed to connect to REST server - is the pvm-rest service started?  "
"Retrying %(try_num)d of %(max_tries)d after %(delay)d seconds."
msgstr ""
"Echec de connexion au serveur REST - le service pvm-rest est -il démarré ? "
"Essai %(try_num)d sur %(max_tries)d après %(delay)d secondes."

#: pypowervm/adapter.py:439
#, python-format
msgid "Session logging on %s"
msgstr "Connexion de session sur %s"

#: pypowervm/adapter.py:503
msgid "Failed to parse a session token from the PowerVM response."
msgstr "Echec d'analyse d'un jeton de session à partir de la réponse PowerVM."

#: pypowervm/adapter.py:505 pypowervm/adapter.py:521
#, python-format
msgid " Body= %s"
msgstr " Corps= %s"

#: pypowervm/adapter.py:519
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "Echec d'analyse d'un chemin de fichier de session à partir de la réponse PowerVM."

#: pypowervm/adapter.py:533
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "Le fichier de jeton %s ne contenait pas de jeton de session lisible."

#: pypowervm/adapter.py:543
#, python-format
msgid "Session logging off %s"
msgstr "Déconnexion de session %s"

#: pypowervm/adapter.py:548
msgid "Problem logging off.  Ignoring."
msgstr "Problème de déconnexion. Opération ignorée."

#: pypowervm/adapter.py:586
msgid "Failed to register for events.  Events will not be used."
msgstr "Echec d'enregistrement pour des événements. Ceux-ci ne seront pas utilisés."

#: pypowervm/adapter.py:667
msgid "job must be a JobRequest element"
msgstr "le travail doit être un élément JobRequest"

#: pypowervm/adapter.py:671
msgid "JobRequest is missing OperationName"
msgstr "JobRequest sans OperationName"

#: pypowervm/adapter.py:685 pypowervm/adapter.py:891 pypowervm/adapter.py:951
#: pypowervm/adapter.py:1047
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "path=%s n'est pas une référence d'API PowerVM"

#: pypowervm/adapter.py:1062 pypowervm/adapter.py:1079
msgid "Invalid file descriptor"
msgstr "Descripteur de fichier non valide"

#: pypowervm/adapter.py:1204 pypowervm/adapter.py:1232
#: pypowervm/adapter.py:1247
msgid "Expected root_id"
msgstr "root_id attendu"

#: pypowervm/adapter.py:1206
msgid "Expected child_type"
msgstr "child_type attendu"

#: pypowervm/adapter.py:1210 pypowervm/adapter.py:1236
#: pypowervm/adapter.py:1241
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "suffix_type=%s inattendu"

#: pypowervm/adapter.py:1213 pypowervm/adapter.py:1244
msgid "Expected suffix_parm"
msgstr "suffix_parm attendu"

#: pypowervm/adapter.py:1215 pypowervm/adapter.py:1234
#: pypowervm/adapter.py:1249
msgid "Expected child_id"
msgstr "child_id attendu"

#: pypowervm/adapter.py:1218 pypowervm/adapter.py:1227
msgid "Unexpected child_id"
msgstr "child_id inattendu"

#: pypowervm/adapter.py:1220 pypowervm/adapter.py:1229
msgid "Unexpected root_id"
msgstr "root_id inattendu"

#: pypowervm/adapter.py:1251
#, python-format
msgid "Unexpected req_method=%s"
msgstr "req_method=%s inattendu"

#: pypowervm/adapter.py:1370
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "Erreur d'analyse syntaxique de réponse XML provenant de PowerVM : %s"

#: pypowervm/adapter.py:1383
msgid "Response is not an Atom feed/entry"
msgstr "La réponse n'est pas un flux/une entrée Atom"

#: pypowervm/adapter.py:1394
msgid "Unexpected HTTP 204 for request"
msgstr "HTTP 204 inattendu pour la demande"

#: pypowervm/adapter.py:1402
msgid "Unexpectedly empty response body"
msgstr "Corps de réponse vide inattendu"

#: pypowervm/adapter.py:1405
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s :\n"
"En-têtes de demande : %(reqheaders)s\n"
"\n"
"Corps de demande : %(reqbody)s\n"
"\n"
"En-têtes de réponse : %(respheaders)s\n"
"\n"
"Corps de réponse : %(respbody)s"

#: pypowervm/adapter.py:1413
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "Erreur Atom pour %(method)s %(path)s : %(reason)s"

#: pypowervm/adapter.py:1455
msgid "Session must not be None"
msgstr "La session ne doit pas être Aucun"

#: pypowervm/adapter.py:1457
msgid "An event listener is already active on the session."
msgstr "Un programme d'écoute d'événement est déjà actif sur la session."

#: pypowervm/adapter.py:1473
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "Echec d'initialisation du programme d'écoute de flux d'événements : %s"

#: pypowervm/adapter.py:1477
#, python-format
msgid "Application id \"%s\" is not unique"
msgstr "L'ID application \"%s\" n'est pas unique"

#: pypowervm/adapter.py:1486
msgid "Shutting down"
msgstr "En cours d'arrêt"

#: pypowervm/adapter.py:1489
msgid "This handler is already subscribed"
msgstr "Ce gestionnaire est déjà abonné"

#: pypowervm/adapter.py:1497
msgid "Handler must be an EventHandler"
msgstr "Le gestionnaire doit être de type EventHandler"

#: pypowervm/adapter.py:1500
msgid "This handler not found in subscriber list"
msgstr "Ce gestionnaire est introuvable dans la liste d'abonnés"

#: pypowervm/adapter.py:1508
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "Arrêt du EventListener pour %s"

#: pypowervm/adapter.py:1512
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "Arrêt du EventListener terminé pour %s"

#: pypowervm/adapter.py:1532
msgid "Error while getting PowerVM events"
msgstr "Erreur lors de l'obtention d'événements PowerVM"

#: pypowervm/adapter.py:1569
#, python-format
msgid "Unexpected EventType=%s"
msgstr "EventType=%s inattendu"

#: pypowervm/adapter.py:1586
msgid "Error while processing PowerVM events"
msgstr "Erreur lors du traitement d'événements PowerVM"

#: pypowervm/exceptions.py:117
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""
"Dérivation impossible du port FC physique approprié pour le WWPN %(wwpn)s."
" Groupes d'attributs étendus VIOS peut-être insuffisants. L'URI VIOS"
" de la requête était %(vio_uri)s."

#: pypowervm/exceptions.py:123
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "Elément introuvable : %(element_type)s %(element)s"

#: pypowervm/exceptions.py:127
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "Partition logique introuvable : %(lpar_name)s"

#: pypowervm/exceptions.py:131
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "L'opération '%(operation_name)s' a échoué. %(error)s"

#: pypowervm/exceptions.py:135
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""
"Echec de l'opération '%(operation_name)s'. Echec d'achèvement de la tâche"
" en %(seconds)d secondes."

#: pypowervm/exceptions.py:140
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Echec de mise hors tension de la machine virtuelle %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:144
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Echec de mise sous tension de la machine virtuelle %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:148
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""
"Impossible de retirer le VLAN %(vlan_id)d car il s'agit de l'ID VLAN"
" principal sur un autre pont de réseau."

#: pypowervm/exceptions.py:153
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""
"Impossible de mettre à disposition le VLAN %(vlan_id)d.  Il semble être "
"contenu dans l'unité '%(dev_name)s' sur le serveur Virtual I/O Server"
" %(vios)s. Cette unité n'est connectée à aucun pont de réseau (carte "
"Ethernet partagée). Retirez manuellement l'unité ou ajoutez-la au pont "
"de réseau avant de continuer."

#: pypowervm/exceptions.py:162
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""
"Une unité logique avec le nom %(lu_name)s existe déjà sur le pool de "
"stockage partagé %(ssp_name)s."

#: pypowervm/exceptions.py:167
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""
"Impossible de trouver un port physique auquel mapper un port FC.  "
"Soit un serveur Virtual I/O Server est indisponible, soit une"
" spécification de port n'est pas adaptée à des ports FC physiques."

#: pypowervm/exceptions.py:174
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"Impossible de démarrer la console sur la machine virtuelle. L'API"
" pypowervm s'exécute en mode non local. La console peut être déployée "
"uniquement si pypowervm se trouve au même endroit que l'API PowerVM."

#: pypowervm/exceptions.py:181
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "La tâche WrapperTask %(name)s ne comporte pas de sous-tâche."

#: pypowervm/exceptions.py:185
msgid "FeedTask can't have an empty feed."
msgstr "La tâche FeedTask ne peut pas avoir de flux vide."

#: pypowervm/exceptions.py:189
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "Le système d'exploitation a refusé l'accès au fichier %(access_file)s."

#: pypowervm/exceptions.py:193
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"Erreur d'E-S rencontrée par l'OS pdt tentative de lecture du fichier "
"%(access_file)s : %(error)s"

#: pypowervm/exceptions.py:198
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "La tâche de migration a échoué. %(error)s"

#: pypowervm/exceptions.py:202
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "Aucune source de chargement pour la machine virtuelle %(vm_name)s"

#: pypowervm/exceptions.py:206
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The "
"parent_entry attribute is not set.  This may be due to using a PV "
"obtained through an unsupported property chain.  The PV must be accessed "
"via VIOS.phys_vols, VG.phys_vols, or "
"VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"Impossible de dériver le codage pg83 pour le hdisk %(dev_name)s. Attribut "
"parent_entry non défini. Cause possible : utilisation d'un PV obtenu via "
"une chaîne de propriété non prise en charge. Le PV doit être accessible "
"via VIOS.phys_vols, VG.phys_vols, ou "
"VIOS.scsi_mappings[n].backing_storage."

#: pypowervm/exceptions.py:214
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most "
"once."
msgstr ""
"Unité %(devname)s détectée %(count)d fois ; Attendue au plus "
"une fois."

#: pypowervm/exceptions.py:231
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "Précisément une partition de gestion attendue ; trouvé %(count)d."

#: pypowervm/exceptions.py:237
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found "
"%(count)d."
msgstr ""
"Précisément une partition attendue avec l'ID %(lpar_id)d ; "
"trouvé %(count)d."

#: pypowervm/exceptions.py:243
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s."
msgstr "Niveau par défaut introuvable sur le pool de stockage partagé %(ssp_name)s."

#: pypowervm/exceptions.py:252
#, python-format
msgid ""
"The device with UDID %(udid)s was not found on any of the Virtual I/O "
"Servers."
msgstr ""
"L'unité avec l'UDID %(udid)s est introuvable sur l'un des serveurs "
"Virtual I/O Server."

#: pypowervm/exceptions.py:257
#, python-format
msgid ""
"There are not enough Virtual I/O Servers to support the virtual machine's"
" device with UDID %(udid)s."
msgstr ""
"Nombre de serveurs Virtual I/O Server insuffisant pour prendre en charge "
"l'unité de la machine virtuelle avec l'UDID %(udid)s."

#: pypowervm/exceptions.py:262
#, python-format
msgid ""
"The expected fabrics (%(fabrics)s) were not found on any of the Virtual "
"I/O Servers."
msgstr ""
"Ensembles de noeuds attendus (%(fabrics)s) introuvable sur l'un des "
"serveurs Virtual I/O Server."

#: pypowervm/exceptions.py:267
#, python-format
msgid ""
"Can not rebuild the virtual machine.  It is using an I/O type of "
"%(io_type)s which is not supported for VM rebuild."
msgstr ""
"Régénération de la machine virtuelle impossible. Elle utilise un "
"type d'E-S %(io_type)s non pris en charge pour ce type d'opération."

#: pypowervm/exceptions.py:272
#, python-format
msgid ""
"The number of VFC slots on the target system (%(rebuild_slots)d) does not"
" match the number of slots on the client system (%(original_slots)d).  "
"Unable to rebuild this virtual machine on this system."
msgstr ""
"Le nombre d'emplacements VFC sur le système cible %(rebuild_slots)d) ne "
"correspond pas au nombre sur le système client %(original_slots)d).  "
"Impossible de régénérer cette machine virtuelle sur le système. "

#: pypowervm/exceptions.py:279
#, python-format
msgid ""
"To register the slot information of the network device a CNA or VNIC "
"adapter is needed. Instead the following was given: %(wrapper)s."
msgstr ""
"Pour enregistrer les infos d'emplacements de l'unité réseau, un "
"adaptateur CNA ou VNIC est requis. Le système suivant a été fourni : %(wrapper)s."

#: pypowervm/exceptions.py:285
#, python-format
msgid ""
"There are not enough active Virtual I/O Servers available. Expected "
"%(exp)d; found %(act)d."
msgstr ""
"Nombre insuffisant de serveurs Virtual I/O Server disponibles. "
"Attendu %(exp)d ; trouvé %(act)d."

#: pypowervm/exceptions.py:290
#, python-format
msgid ""
"No Virtual I/O Servers are available.  Attempted to wait for a VIOS to "
"become active for %(wait_time)d seconds.  Please check the RMC "
"connectivity between the PowerVM NovaLink and the Virtual I/O Servers."
msgstr ""
"Aucun serveur Virtual I/O Server disponible. Tentative d'attente d'un "
"VIOS actif pendant %(wait_time)d secondes. Vérifiez la connectivité RMC "
"entre les serveurs PowerVM NovaLink et Virtual I/O Server."

#: pypowervm/exceptions.py:300
#, python-format
msgid ""
"Could not find any SR-IOV adapters in Sriov mode and Running state.\n"
"Location | Mode | State\n"
"%(sriov_loc_mode_state)s"
msgstr ""
"Adaptateurs SR-IOV introuvables en mode Sriov et à l'état d'exécution.\n"
"Emplacement | Mode | Etat\n"
"%(sriov_loc_mode_state)s"

#: pypowervm/exceptions.py:305
#, python-format
msgid ""
"Unable to fulfill minimum redundancy requirement of %(min_vfs)d.  Found "
"%(found_vfs)d viable backing device(s)."
msgstr ""
"Impossible de satisfaire exigence de redondance mini de %(min_vfs)d. "
"Trouvé %(found_vfs)d unité(s) de support viable(s)."

#: pypowervm/exceptions.py:310
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"Impossible de localiser le groupe de volumes %(vol_grp)s dans lequel "
"stocker le support optique virtuel. Impossible de créer le référentiel "
"de supports."

#: pypowervm/exceptions.py:316
#, python-format
msgid ""
"The ManagedSystem update was not attempted because changes were requested"
" to one or more SR-IOV physical ports which are in use by vNICs.\n"
"%(warnings)s"
msgstr ""
"Mise à jour de ManagedSystem inattendue car changements demandés "
"pour un/plusieurs ports physiques SR-IOV utilisés par des vNIC.\n"
"%(warnings)s"

#: pypowervm/exceptions.py:322
#, python-format
msgid "Unable to create VNC based virtual terminal: %(err)s"
msgstr "Impossible de créer un terminal virtuel de base VNC : %(err)s"

#: pypowervm/util.py:124
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"Le groupe d'attributs étendus proposé '%(arg_xag)s' ne correspond pas "
"au groupe existant '%(path_xag)s'"

#: pypowervm/util.py:260
msgid "Certificate has expired."
msgstr "Le certificat est arrivé à expiration."

#: pypowervm/util.py:410
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "Préfixe et suffixe ensemble ne doivent pas dépasser %d caractères."

#: pypowervm/util.py:415
msgid "Total length must be at least 1 character."
msgstr "La longueur totale doit être d'au moins 1 caractère."

#: pypowervm/util.py:438
msgid "The name parameter must be at least one character long."
msgstr "La longueur du paramètre de nom doit être d'au moins un caractère."

#: pypowervm/util.py:441
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr "Le paramètre de nom ne doit pas dépasser %d caractères quand trunk_ok est False."

#: pypowervm/util.py:539
msgid "Developer error: partial parent specification."
msgstr "Erreur développeur : spécification parent partielle."

#: pypowervm/util.py:544
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"Erreur développeur : parent_type doit être un type de schéma chaîne "
" schéma ou un sous-classe d'encapsuleur (Wrapper)"

#: pypowervm/util.py:596
#, python-format
msgid "Invalid value '%(bad_val)s'.  Expected one of %(good_vals)s, or a list."
msgstr "Valeur non valide '%(bad_val)s'. Attendue : une parmi %(good_vals)s ou une liste."

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "DEMANDE : %s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "REPONSE : %s"

#: pypowervm/tasks/cluster_ssp.py:108
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "Attente de fin d'importation(s) en cours. Marquer unité(s) logique(s) : %s"

#: pypowervm/tasks/cluster_ssp.py:137
msgid "Abdicating in favor of in-progress upload."
msgstr "Abdication en faveur de l'importation en cours."

#: pypowervm/tasks/cluster_ssp.py:147
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "Abdication de l'importation en faveur du marqueur %s."

#: pypowervm/tasks/cluster_ssp.py:200
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "Utilisation d'une image déjà importée - unité logique %s"

#: pypowervm/tasks/cluster_ssp.py:210
#, python-format
msgid "Creating marker LU %s"
msgstr "Création marqueur unité logique %s"

#: pypowervm/tasks/cluster_ssp.py:226
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "Importation vers image unité logique %(lu)s (marqueur %(mkr)s)."

#: pypowervm/tasks/cluster_ssp.py:237
#, python-format
msgid "Removing failed LU %s."
msgstr "Echec du retrait de l'unité logique %s."

#: pypowervm/tasks/cna.py:120
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "Impossible de trouver le commutateur virtuel %s sur le système."

#: pypowervm/tasks/cna.py:147
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "Impossible de trouver un VLAN valide pour le commutateur virtuel %s."

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"Erreur d'obtention de surcharge de mémoire hôte pour l'hôte avec l'UUID "
"'%(host)s' : %(error)s."

#: pypowervm/tasks/partition.py:273
#, python-format
msgid ""
"Timed out waiting for the RMC state of all the powered on Virtual I/O "
"Servers to be active. Wait time was: %(time)d seconds. VIOSes that did "
"not go active were: %(vioses)s."
msgstr ""
"Délai d'attente dépassé pour l'état RMC de tous les serveurs Virtual I/O "
"Server sous tension. Temps d'attente : %(time)d secondes. VIOS non passés"
" à l'état actif : %(vioses)s."

#: pypowervm/tasks/power.py:216
#, python-format
msgid "Error: %s"
msgstr "Erreur : %s"

#: pypowervm/tasks/power.py:263
#, python-format
msgid ""
"Error invalidating adapter cache for LPAR  %(lpar_name) with UUID "
"%(lpar_uuid)s: %(exc)s"
msgstr ""
"Erreur d'invalidation du cache d'adaptateur pour LPAR  %(lpar_name) "
"avec l'UUID %(lpar_uuid)s : %(exc)s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "Nouvelle tentative de modification du mappage SCSI."

#: pypowervm/tasks/scsi_mapper.py:98
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Mappage existant détecté d'élément de stockage %(stg_type)s %(stg_name)s "
"depuis le serveur Virtual I/O Server %(vios_name)s vers la partition "
"client %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:117
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Création du mappage de l'élément de stockage %(stg_type)s %(stg_name)s "
"depuis le serveur Virtual I/O Server %(vios_name)s vers la partition "
"client %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:426
msgid "Must not specify both match_func and stg_elem."
msgstr "match_func et stg_elem ne doivent pas être spécifiés ensemble."

#: pypowervm/tasks/slot_map.py:194
msgid ""
"The register_cna method is deprecated! Please use the register_vnet "
"method."
msgstr ""
"La méthode register_cna est obsolète. Utilisez la méthode "
"register_vnet. "

#: pypowervm/tasks/slot_map.py:204
msgid "The drop_cna method is deprecated! Please use the drop_vnet method."
msgstr "Méthode drop_cna obsolète. Utilisez la méthode drop_vnet."

#: pypowervm/tasks/sriov.py:291
#, python-format
msgid ""
"SR-IOV Physical Port at location %(loc_code)s is backing a vNIC belonging"
" to LPAR %(lpar_name)s (LPAR UUID: %(lpar_uuid)s; vNIC UUID: "
"%(vnic_uuid)s)."
msgstr ""
"Le port physique SR-IOV à l'emplacement %(loc_code)s support un vNIC "
"appartenant à une LPAR %(lpar_name)s (UUID LPAR : %(lpar_uuid)s; UUID "
"vNIC : %(vnic_uuid)s)."

#: pypowervm/tasks/sriov.py:408
msgid ""
"Making changes to the following SR-IOV physical port labels even though "
"they are in use by vNICs:"
msgstr ""
"Changements apports aux labels de port physique SR-IOV suivants même si "
"ils sont utilisés par des contrôleurs vNIC:"

#: pypowervm/tasks/storage.py:325
#, python-format
msgid "Unable to cleanup after file upload. File uuid: %s"
msgstr "Impossible de nettoyer après chargement du fichier. UUID fichier : %s"

#: pypowervm/tasks/storage.py:384
msgid ""
"The crt_lu_linked_clone method is deprecated!  Please use the crt_lu "
"method (clone=src_lu, size=lu_size_gb)."
msgstr ""
"La méthode crt_lu_linked_clone est obsolète. Utilisez la méthode "
"crt_lu (clone=src_lu, taille=lu_size_gb)."

#: pypowervm/tasks/storage.py:435
#, python-format
msgid "Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr "L'unité logique de disque %(luname)s n'a pas d'unité logique d'image de support. (UDID : %(udid)s) "

#: pypowervm/tasks/storage.py:479
msgid "Unable to locate new vDisk on file upload."
msgstr "Impossible de localiser le nouveau vDisk sur le téléchargement de fichier."

#: pypowervm/tasks/storage.py:528
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"Unité ignorée car son UDID est absent :\n"
"%s"

#: pypowervm/tasks/storage.py:534
#, python-format
msgid "Device %s not found in list."
msgstr "Unité %s introuvable dans la liste."

#: pypowervm/tasks/storage.py:563
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "Suppression du disque virtuel %(vdisk)s du groupe de volumes %(vg)s"

#: pypowervm/tasks/storage.py:586
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "Suppression de l'unité optique virtuelle %(vopt)s du groupe de volumes %(vg)s"

#: pypowervm/tasks/storage.py:642
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "Retrait de l'unité logique %(lu_name)s (UDID %(lu_udid)s)"

#: pypowervm/tasks/storage.py:646
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"Unité logique %(lu_name)s introuvable - elle a peut-être été supprimée  "
"en externe. (UDID : %(lu_udid)s)"

#: pypowervm/tasks/storage.py:664
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"Retrait de l'unité logique d'image %(lu_name)s car elle n'est plus "
"utilisée. (UDID : %(lu_udid)s)"

#: pypowervm/tasks/storage.py:669
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "Unité logique de support %(lu_name)s introuvable. (UDID : %(lu_udid)s)"

#: pypowervm/tasks/storage.py:695
msgid "Developer error: Either tier or lufeed is required."
msgstr "Erreur développeur : tier ou lufeed requis."

#: pypowervm/tasks/storage.py:700
msgid "Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr "Erreur développeur : le paramètre lufeed doit inclure LUEnt EntryWrappers."

#: pypowervm/tasks/storage.py:707
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "Suppression de l'unité logique %(lu_name)s (UDID : %(lu_udid)s)"

#: pypowervm/tasks/storage.py:712
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band."
"  (UDID: %(lu_udid)s)"
msgstr ""
"HttpError ignoré pour l'unité logique %(lu_name)s peut-être été supprimé en externe."
"  (UDID : %(lu_udid)s)"

#: pypowervm/tasks/storage.py:765
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""
"Retrait de %(num_maps)d mappages %(stg_type)s orphelin du VIOS "
"%(vios_name)s."

#: pypowervm/tasks/storage.py:791
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "Retrait de %(num_maps)d mappages VFC sans port du VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:818
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"Retrait de %(num_maps)d mappages %(stg_type)s associés à l'ID partition "
"logique %(lpar_id)d depuis le VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:885
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot "
"be determined whether it is still in use.  Manual verification and "
"cleanup may be necessary."
msgstr ""
"Pas de retrait du stockage %(stg_name)s de type %(stg_type)s car pas "
"possible de déterminer si toujours utilisé. Vérification et nettoyage "
"manuels peut-être nécessaires."

#: pypowervm/tasks/storage.py:896
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"Elément de stockage %(stg_name)s ignoré par l'épuration car de type "
"inattendu %(stg_type)s."

#: pypowervm/tasks/storage.py:914
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"Epuration des %(vdcount)d disques virtuels suivants du VIOS %(vios)s : "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:922
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"Epuration des %(vocount)d unités optiques virtuelles suivantes du VIOS "
"%(vios)s :  %(volist)s"

#: pypowervm/tasks/storage.py:990
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"Epuration ignorée des mappages %(stg_type)s du VIOS %(vios_name)s pour "
"les ID LPAR car ces partitions logiques existent : %(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:527
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"Impossible de trouver le VIOS approprié. Le contenu fourni semble "
"insuffisant. Données de contenu : \n"
" %s)"

#: pypowervm/tasks/vfc_mapper.py:556
#, python-format
msgid ""
"The matched VFC port map has no backing port set. Adding %(port)s to "
"mapping for client wwpns: %(wwpns)s"
msgstr ""
"La mappe de port VFC correspondante n'a pas de port de support défini. "
"Ajout de %(port)s au mappage pour les WWPN client : %(wwpns)s"

#: pypowervm/tasks/vopt.py:73
msgid ""
"An error occurred querying the virtual optical media repository.  "
"Attempting to re-establish connection with a virtual optical media "
"repository"
msgstr ""
"Erreur lors de l'interrogation du référentiel de supports optiques virtuels.  "
"Tentative de restauration de la connexion au référentiel de supports "
"optiques virtuels"

#: pypowervm/tasks/vterm.py:78
msgid "Unable to close vterm."
msgstr "Impossible de fermer vterm."

#: pypowervm/tasks/vterm.py:131
#, python-format
msgid "Invalid output on vterm open.  Trying to reset the vterm.  Error was %s"
msgstr "Sortie non valide sur vterm ouvert. Tentative de réinitialisation du vterm. Erreur : %s"

#: pypowervm/tasks/vterm.py:341
#, python-format
msgid "VNCRepeater Server Listening on ip=%(ip)s port=%(port)s"
msgstr "Serveur VNCRepeater en mode écoute sur ip=%(ip)s port=%(port)s"

#: pypowervm/tasks/vterm.py:504
#, python-format
msgid "Error negotiating SSL for VNC Repeater: %s"
msgstr "Erreur de négociation SSL pour le répéteur VNC : %s"

#: pypowervm/tasks/hdisk/_fc.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""
"Echec de reconnaissance de hdisk. Epuration du stockage périmé pour "
"les ID partition logique %s avant nouvelle tentative."

#: pypowervm/tasks/hdisk/_fc.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "La reprise de LUA a abouti. Unité trouvée : %s"

#: pypowervm/tasks/hdisk/_fc.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "Erreur ITL rencontrée : %s"

#: pypowervm/tasks/hdisk/_fc.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "Unité %s actuellement utilisée."

#: pypowervm/tasks/hdisk/_fc.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "Unité %s détectée avec UDID inconnu."

#: pypowervm/tasks/hdisk/_fc.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "Echec de reconnaissance de l'unité : %s"

#: pypowervm/tasks/hdisk/_fc.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "Erreur CLIRunner : %s"

#: pypowervm/tasks/hdisk/_fc.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"Le travail QUERY_INVENTORY LUARecovery a abouti, mais le résultat "
"ne contenait ni OutputXML ni StdOut."

#: pypowervm/tasks/hdisk/_fc.py:475
#, python-format
msgid "QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr "QUERY_INVENTORY a produit un bloc XML non valide (%(chunk)s).  Erreur : %(err)s"

#: pypowervm/tasks/hdisk/_fc.py:483
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"Echec de recherche du descripteur pg83 dans la sortie XML :\n"
"%s"

#: pypowervm/tasks/hdisk/_iscsi.py:62
#, python-format
msgid "Expected IQN: %(IQN)s not found on iscsi target %(host_ip)s"
msgstr "IQN attendu %(IQN)s introuvable sur la cible iscsi %(host_ip)s"

#: pypowervm/tasks/monitor/util.py:421
msgid ""
"Metric data is not available.  This may be due to the metrics being "
"recently initialized."
msgstr ""
"Données de mesure indisponibles. Peut être dû aux métriques "
"récemment initialisées."

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "Ceci est un test"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "Il n'existe pas de traduction pour ce message"

#: pypowervm/utils/retry.py:203
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"Tentative %(retry)d sur un total de %(total)d pour l'URI %(uri)s. Erreur "
"code de réponse de nouvel essai : %(resp_code)s"

#: pypowervm/utils/retry.py:210
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"Echec tentative %(retry)d sur %(total)d. Nouvelle tentative. Exception :\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "Vous devez indiquer EntryWrapper ou EntryWrapperGetter."

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "Indiquez une sous-tâche valide."

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "Nom 'provides' en double %s."

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s ne comporte pas de sous-tâche. Pas d'opération exécutée."

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "Indiquez une liste de EntryWrappers ou un FeedGetter."

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s n'a aucun sous-tâches; exécution instruction no-op."

#: pypowervm/utils/validation.py:161
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"Ressources %(res_name)s disponibles insuffisantes sur l'hôte pour la "
"machine virtuelle '%(instance_name)s' (%(requested)s demandées, "
"%(avail)s disponibles)"

#: pypowervm/utils/validation.py:189
msgid "memory"
msgstr "mémoire"

#: pypowervm/utils/validation.py:210
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"La machine virtuelle doit être hors tension avant changement de la "
"mémoire mini ou maxi. Mettez la machine %s hors tension et réessayez."

#: pypowervm/utils/validation.py:215
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"La machine virtuelle doit être mise hors tension avant changement du "
"facteur d'expansion. Mettez la machine %s hors tension et réessayez."

#: pypowervm/utils/validation.py:302
msgid "CPUs"
msgstr "UC"

#: pypowervm/utils/validation.py:318
msgid "processing units"
msgstr "unités de traitement"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"La machine virtuelle doit être hors tension avant changement de la "
"processeurs mini ou maxi. Mettez la machine %s hors tension et réessayez."

#: pypowervm/utils/validation.py:369
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"La machine virtuelle doit être hors tension avant changement de la "
"processeur mini ou maxi. Mettez la machine %s hors tension et réessayez."

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"La machine virtuelle doit être hors tension avant changement du mode de "
"compatibilité processeur. Mettez la machine %s hors tension et réessayez."

#: pypowervm/utils/validation.py:393
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""
"La machine virtuelle doit être hors tension avant changement du mode de "
"traitement. Mettez la machine %s hors tension et réessayez."

#: pypowervm/utils/validation.py:422
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Le nombre de processeurs souhaité %(vcpus)d) ne doit pas dépasser le "
"nombre maximal autorisé par partition (%(max_allowed)d) pour la machine "
"virtuelle '%(instance_name)s'."

#: pypowervm/utils/validation.py:434
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Le nombre maximal de processeurs (%(vcpus)d) ne doit pas dépasser la "
"limite processeur de capacité système (%(max_allowed)d) pour la machine "
"virtuelle '%(instance_name)s'."

#: pypowervm/utils/validation.py:506
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"La machine virtuelle doit être mise hors tension avant changement de la "
"fonction de redémarrage à distance. Mettez la machine %s hors tension et"
" réessayez."

#: pypowervm/wrappers/base_partition.py:421
msgid "Partition does not have an active RMC connection."
msgstr "La partition n'a pas de connexion RMC active."

#: pypowervm/wrappers/base_partition.py:424
#, python-format
msgid "Partition does not have an active DLPAR capability for %s."
msgstr "La partition n'a pas de fonction DLPAR active pour %s."

#: pypowervm/wrappers/base_partition.py:436
msgid "I/O"
msgstr "E-S"

#: pypowervm/wrappers/base_partition.py:446
msgid "Memory"
msgstr "Mémoire"

#: pypowervm/wrappers/base_partition.py:456
msgid "Processors"
msgstr "Processeurs"

#: pypowervm/wrappers/base_partition.py:632
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos non valide '%s'."

#: pypowervm/wrappers/base_partition.py:643
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "BootMode non valide '%s'."

#: pypowervm/wrappers/base_partition.py:1405
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "IOSlot.adapter obsolète. Utilisez IOSlot.io_adapter à la place."

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the"
" master console for the pool."
msgstr ""
"Impossible déterminer code MTMS de la console de gestion maître (type "
"machine, modèle, n° série) depuis %(identifier)s car aucune %(param)s"
" marquée comme console maître du pool."

#: pypowervm/wrappers/entry_wrapper.py:251
msgid "Cannot set uuid."
msgstr "Impossible de définir l'uuid."

#: pypowervm/wrappers/entry_wrapper.py:443
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "Impossible de convertir %(property_name)s='%(value)s' dans l'objet %(pvmobject)s"

#: pypowervm/wrappers/entry_wrapper.py:586
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"Refus de définition de href sur plusieurs liens.\n"
"Chemin : %{path}s\n"
"Nombre de liens trouvés : %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:630
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "Refus de construction et d'encapsulation d'élément sans balise."

#: pypowervm/wrappers/entry_wrapper.py:755
msgid "Response is missing 'entry' property."
msgstr "Propriété 'entry' manquante dans la réponse."

#: pypowervm/wrappers/entry_wrapper.py:769
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "Indiquez une réponse ou une entrée pour l'encapsulation. Obtenu %s"

#: pypowervm/wrappers/entry_wrapper.py:856
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to"
" retrieve a CHILD object."
msgstr ""
"Erreur développeur : indiquez 'parent' ou ('parent_type' et 'parent_uuid')"
" pour extraire un objet CHILD."

#: pypowervm/wrappers/entry_wrapper.py:861
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "Indiquez 'uuid' ou 'root_id' lors de la demande d'objet ROOT."

#: pypowervm/wrappers/entry_wrapper.py:874
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD "
"feed or entry."
msgstr ""
"parent_type et parent_uuid obligatoires quand extraction d'un flux ou "
"d'une entrée CHILD."

#: pypowervm/wrappers/entry_wrapper.py:877
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "Indiquez l'UUID du parent via le paramètre parent_uuid."

#: pypowervm/wrappers/entry_wrapper.py:881
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "Indiquez 'uuid' ou 'child_id' lors de la demande d'objet CHILD."

#: pypowervm/wrappers/entry_wrapper.py:975
msgid "Parent UUID specified without parent type."
msgstr "UUID parent spécifié sans type parent."

#: pypowervm/wrappers/entry_wrapper.py:978
msgid "The search() method requires exactly one key=value argument."
msgstr "La méthode search() requiert exactement un argument key=value."

#: pypowervm/wrappers/entry_wrapper.py:1009
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "La classe d'encapsuleur %(class)s ne prend pas en charge le critère de recherche '%(key)s'."

#: pypowervm/wrappers/entry_wrapper.py:1109
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using"
" it will result in a no-op.  At worst, it will give you incurable etag "
"mismatch errors."
msgstr ""
"Paramètre 'xag' sur EntryWrapper.update obsolète. Au mieux, l'utiliser"
" sera sans résultat. Au pire, génèrera des erreurs de concordance de "
"etag non résolvables."

#: pypowervm/wrappers/entry_wrapper.py:1377
msgid "No such child element."
msgstr "Aucun élément enfant de ce type."

#: pypowervm/wrappers/entry_wrapper.py:1438
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "Impossible de définir l'UUID sur l'encapsuleur sans métadonnées."

#: pypowervm/wrappers/entry_wrapper.py:1443
#, python-format
msgid "uuid value not valid: %s"
msgstr "Valeur d'UUID non valide : %s"

#: pypowervm/wrappers/entry_wrapper.py:1498
msgid "Must specify a Wrapper subclass."
msgstr "Vous devez définir une sous-classe d'encapsuleur."

#: pypowervm/wrappers/entry_wrapper.py:1507
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "Vous devez indiquer la classe parent et l'UUID parent, ou aucun des deux."

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "Travail %(job_id)s en cours de surveillance depuis %(time)i secondes."

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely"
" for termination."
msgstr ""
"Emission de demande d'annulation du travail %(job_id)s. Le travail sera"
" interrogé indéfiniment pour l'arrêt."

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "Travail %s non supprimé. Le travail est à l'état d'exécution."

#: pypowervm/wrappers/logical_partition.py:168
msgid "LPAR is not in an active state."
msgstr "La partition logique n'est pas à l'état actif."

#: pypowervm/wrappers/logical_partition.py:178
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "Le système cible n'est pas compatible avec la fonction de mobilité de partition IBM i."

#: pypowervm/wrappers/logical_partition.py:182
msgid "IBM i LPAR does not have restricted I/O."
msgstr "La partition logique IBM i n'a pas restriction d'E-S."

#: pypowervm/wrappers/logical_partition.py:186
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "Le système source n'est pas compatible avec la fonction de mobilité de partition IBM i."

#: pypowervm/wrappers/logical_partition.py:190
msgid "LPAR does not have an active RMC connection."
msgstr "La partition logique n'a pas de connexion RMC active."

#: pypowervm/wrappers/logical_partition.py:193
msgid "LPAR is the management partition"
msgstr "La partition logique est la partition de gestion"

#: pypowervm/wrappers/logical_partition.py:197
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "La partition logique n'est pas disponible pour LPM en raison de fonctions DLPAR manquantes."

#: pypowervm/wrappers/logical_partition.py:214
#: pypowervm/wrappers/logical_partition.py:223
#: pypowervm/wrappers/logical_partition.py:231
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a "
"NovaLink environment."
msgstr ""
"Ceci n'est pas la propriété que vous recherchez. Utilisez srr_enabled "
"dans un environnement NovaLink."

#: pypowervm/wrappers/logical_partition.py:267
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPL source non valide '%s'."

#: pypowervm/wrappers/storage.py:633
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV a encodé le descripteur pg83 \"%(pg83_raw)s\", mais n'a pas pu le décoder. "
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:163
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please"
" use values from pypowervm.const.XAG instead."
msgstr ""
"Propriété 'xags' de la classe VIOS EntryWrapper obsolète. Utilisez"
" à la place des valeurs de pypowervm.const.XAG."

#: pypowervm/wrappers/virtual_io_server.py:400
msgid "Partition of VIOS type is not LPM capable"
msgstr "La partition de type VIOS n'est pas compatible LPM"

#: pypowervm/wrappers/virtual_io_server.py:647
msgid "Can't specify target device LUA without a backing storage device!"
msgstr "Impossible de spécifier de LUA d'unité cible sans unité de stockage de secours."


# ENGL1SH_VERS10N 26021_47 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG PV132AAP001 1
